name: Coverage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin
      options: --security-opt seccomp=unconfined

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install ctags on Linux
      run: |
        apt-get update
        apt-get install exuberant-ctags
    - name: git submodule init
      run: |
        git submodule init
        git submodule update
    - name: Run tests
      run: cargo tarpaulin -v --out Xml -- --test-threads=1
    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
