name: Periodic

on:
  schedule:
  - cron: 0 0 * * SUN

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install ctags on Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install exuberant-ctags
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      run: cargo test
