name: Regression

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Install ctags
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install exuberant-ctags
    - name: Install ctags
      if: matrix.os == 'macOS-latest'
      run: |
        brew update
        brew install --HEAD universal-ctags/universal-ctags/universal-ctags
        brew install git-lfs
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      run: cargo test
